---

- name: install message queue for Ubuntu
  tags: ubuntu
  apt:
    name: rabbitmq-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: add Rabbitmq deploy user
  rabbitmq_user:
    user: openstack
    password: diones
    tags: administrator,deploy
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
